"""empty message

Revision ID: eb42fcfea6e9
Revises: bd51aec2a70a
Create Date: 2020-07-05 11:12:41.892965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb42fcfea6e9'
down_revision = 'bd51aec2a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'image')
    # ### end Alembic commands ###
